name: app_core
description: Core framework package for apps of Stackwares
version: 0.0.1
homepage: https://stackwares.com

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  get: ^4.6.5

  # ICONS
  line_icons: ^2.0.1 # icons
  unicons: ^2.1.0
  iconsax: ^0.0.8

  # ANIMATIONS
  simple_animations: ^5.0.0+2
  sa4_migration_kit: ^1.0.0
  flutter_animate: ^1.0.0

  # DESKTOP
  system_tray: ^2.0.2
  launch_at_startup: ^0.2.0
  window_manager: ^0.2.7
  hotkey_manager: ^0.1.7
  protocol_registry: ^0.0.5 # windows, and linux App Links URI

  # UI
  extended_image: ^6.3.1
  flex_color_scheme: 6.0.1 # themes
  flutter_displaymode: ^0.4.0 # allow higher refresh rates
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1

  # IO
  hive: ^2.2.3 # database
  hive_flutter: ^1.1.0
  path: ^1.8.1
  path_provider: ^2.0.11

  # UTILS
  console_mixin: ^0.0.1
  url_launcher: ^6.1.6
  supercharged: ^2.1.1 # useful utils
  flutter_local_notifications: ^12.0.2
  either_dart: ^0.2.0 # functional programming + error handling
  share_plus: ^6.0.1 # exporting files and sharing texts
  app_review: ^2.1.2+1
  app_settings: ^4.1.8
  intl: ^0.17.0 # date formatting
  uuid: ^3.0.6
  timeago: ^3.3.0
  app_links: ^3.3.0
  permission_handler: ^10.2.0
  easy_debounce: ^2.0.2+1
  sentry_flutter: ^6.13.1 # error reporting for windows and linux

  # SECURITY
  local_auth: ^2.1.2

  # FIREBASE
  firebase_core: 2.1.0
  firebase_analytics: 10.0.2
  firebase_crashlytics: 3.0.2
  firebase_performance: 0.9.0+2
  cloud_functions: ^4.0.2
  # -- FIREBASE DESKTOP --
  firebase_dart: ^1.0.11
  firebase_core_desktop: 1.0.2
  firebase_functions_desktop: 0.2.0+3
  firebase_core_platform_interface: 4.5.1
  # -- FIREBASE DESKTOP --

  # API / NETWORKS
  purchases_flutter: ^4.3.0
  http: ^0.13.5
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  supabase: 1.0.1

  # INFO
  device_info_plus: 7.0.1
  platform_device_id: ^1.0.1
  package_info_plus: ^3.0.1

dependency_overrides:
  package_info_plus: ^3.0.1
  firebase_core: ^2.1.0
  cloud_functions: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  icons_launcher: ^2.0.5
  flutter_native_splash: ^2.2.11
  build_runner: ^2.3.2
  dart_code_metrics: ^4.21.2 # checking unused stuffs
  hive_generator: ^2.0.0 # hive database
  # msix: ^3.6.3

flutter:
  #