name: app_core
description: Core framework package for apps of Stackwares
version: 0.0.1
homepage: https://stackwares.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  get: ^4.6.5

  # ICONS
  line_icons: ^2.0.3 # icons
  lucide_icons: ^0.257.0

  # ADS
  stack_appodeal_flutter: ^3.0.2

  # ANIMATIONS
  simple_animations: ^5.0.2
  sa4_migration_kit: ^1.0.0
  flutter_animate: ^4.2.0

  # DESKTOP
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  window_manager: ^0.3.2
  hotkey_manager: ^0.1.8

  # UI
  extended_image: ^8.0.2
  flex_color_scheme: ^7.1.2 # themes
  flutter_displaymode: ^0.6.0 # allow higher refresh rates
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.4
  locale_emoji_flutter: ^0.2.1

  # IO
  hive: ^2.2.3 # database
  hive_flutter: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_secure_storage: ^8.0.0

  # UTILS
  console_mixin: ^0.0.1
  url_launcher: ^6.1.12
  supercharged: ^2.1.1 # useful utils
  flutter_local_notifications: ^15.1.0+1
  either_dart: ^1.0.0 # functional programming + error handling
  in_app_review: ^2.0.6
  app_settings: ^5.0.0
  intl: ^0.18.1 # date formatting
  uuid: ^3.0.7
  timeago: ^3.5.0
  permission_handler: ^10.4.2
  easy_debounce: ^2.0.3
  sentry_flutter: ^7.8.0 # error reporting for windows and linux

  # SECURITY
  local_auth: ^2.1.6

  # FIREBASE
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_messaging: ^14.6.4

  # API / NETWORKS
  purchases_flutter: ^5.3.0
  connectivity_plus: ^4.0.1
  supabase_flutter: ^1.10.6
  supabase_auth_ui: ^0.2.0

  # INFO
  device_info_plus: 9.0.2
  platform_device_id: ^1.0.1
  package_info_plus: ^4.0.2

# dependency_overrides:

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  #
