name: app_core
description: Core framework package for apps of Stackwares
version: 0.0.1
homepage: https://stackwares.com
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # STATE MANAGEMENT
  get: ^4.6.6
  # ICONS
  iconsax: ^0.0.8
  line_icons: ^2.0.3 # icons
  lucide_icons: ^0.257.0
  # ADS
  stack_appodeal_flutter: ^3.2.1
  # ANIMATIONS
  flutter_animate: ^4.4.1
  # DESKTOP
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  window_manager: ^0.3.7
  hotkey_manager: ^0.2.0
  # UI
  extended_image: ^8.2.0
  # image_network:
  #   git:
  #     url: https://github.com/oliverbytes/image_network.git

  image_network:
    path: ../../Others/image_network
  flex_color_scheme: ^7.3.1 # themes
  flutter_displaymode: ^0.6.0 # allow higher refresh rates
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  locale_emoji_flutter: ^0.2.1
  quick_actions: ^1.0.7
  # IO
  hive: ^2.2.3 # database
  hive_flutter: ^1.1.0
  # TODO: NEED UPDATE
  path: ^1.8.3
  # TODO: NEED UPDATE
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  # UTILS
  console_mixin: ^0.0.1
  url_launcher: ^6.2.4
  supercharged: ^2.1.1 # useful utils
  flutter_local_notifications: ^16.3.2
  either_dart: ^1.0.0 # functional programming + error handling
  in_app_review: ^2.0.8
  app_settings: ^5.1.1
  # TODO: NEED UPDATE
  intl: ^0.18.1 # date formatting # NEED UPDATE
  # TODO: NEED UPDATE
  uuid: ^3.0.7
  timeago: ^3.6.0
  permission_handler: ^11.2.0
  easy_debounce: ^2.0.3
  sentry_flutter: ^7.15.0 # error reporting for windows and linux
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.2 # securing the api
  # SECURITY
  local_auth: ^2.2.0
  # FIREBASE
  firebase_core: ^2.25.5
  firebase_analytics: ^10.8.7
  firebase_crashlytics: ^3.4.16
  firebase_performance: ^0.9.3+15
  firebase_messaging: ^14.7.17
  # API / NETWORKS
  purchases_flutter: ^6.22.0
  purchases_ui_flutter: ^6.22.0
  connectivity_plus: ^5.0.2
  supabase_flutter: ^2.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  # INFO
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  # platform_device_id:
  #   git:
  #     url: https://github.com/oliverbytes/platform_device_id.git
  #     path: platform_device_id

flutter:
  #
