name: app_core
description: Core framework package for apps of Stackwares
version: 0.0.1
homepage: https://stackwares.com
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # STATE MANAGEMENT
  get: ^4.6.6
  # ICONS
  icons_plus: ^5.0.0
  # ADS
  stack_appodeal_flutter: ^3.2.1
  # ANIMATIONS
  flutter_animate: ^4.5.0
  # DESKTOP
  launch_at_startup: ^0.2.2
  window_manager: ^0.3.8
  hotkey_manager: ^0.2.2
  # UI
  flex_color_scheme: ^7.3.1 # themes
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  locale_emoji_flutter: ^0.2.1
  quick_actions: ^1.0.7
  extended_image: ^8.2.0
  image_network:
    path: ../../Others/image_network
  # IO
  hive: ^2.2.3 # database
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.1.1
  # UTILS
  console_mixin: ^0.0.1
  url_launcher: ^6.2.6
  flutter_local_notifications: ^17.1.2
  either_dart: ^1.0.0 # functional programming + error handling
  in_app_review: ^2.0.9
  app_settings: ^5.1.1
  # TODO: NEED UPDATE
  intl: ^0.18.1 # date formatting # NEED UPDATE
  uuid: ^4.4.0
  timeago: ^3.6.1
  permission_handler: ^11.3.1
  easy_debounce: ^2.0.3
  # sentry_flutter: ^7.18.0 # error reporting for windows and linux
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.0 # securing the api
  # SECURITY
  local_auth: ^2.2.0
  # FIREBASE
  firebase_core: ^2.28.0
  firebase_analytics: ^10.10.0
  firebase_crashlytics: ^3.5.0
  firebase_performance: ^0.9.4
  firebase_messaging: ^14.8.0
  # API / NETWORKS
  purchases_flutter: ^6.29.0
  # purchases_ui_flutter: ^6.22.0
  connectivity_plus: ^6.0.3
  supabase_flutter: ^2.5.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  # INFO
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  # platform_device_id:
  #   git:
  #     url: https://github.com/oliverbytes/platform_device_id.git
  #     path: platform_device_id

flutter:
  #
